### ISSUE TITLE
`.pager` failed to find the issue it just created

### ISSUE THREAD

**Issue by tcampbell** [hubot-scripts/hubot-pager-me#106]
`.pager` (failed)[https://github.slack.com/archives/C0FNNUEV7/p1506935351000307] to page, saying it could not find the incident it just thought it created:

```
.pager trigger sophaskins Nobody can deploy. See dotcom-ops.

@_: :pager: triggered! now assigning it to the right user...
@_: Couldn't find the incident we just created to reassign. Please try again :/
```

Alerting should not fail like this.  They had to page the oncaller directly (by name).  We need to determine the root cause of this failure and the actual error rate **and** look into what kind of retries/queuing we can do to ensure delivery.

https://github.slack.com/messages/C0CA60KQB/search/%E2%80%9Cfind%20the%20incident%20we%20just%20created%E2%80%9D/ shows a history of failures

Similar to https://github.com/github/ninesapp/issues/639?

**Comment by tcampbell** [comment]
Errors:

The recent incident that made us notice:
- https://github.slack.com/archives/C0FNNUEV7/p1506935358000362
- https://github.slack.com/archives/C0FNNUEV7/p1506935332000325
- https://github.slack.com/archives/C0FNNUEV7/p1506935272000277
- https://github.slack.com/archives/C0FNNUEV7/p1506935151000145

Earlier instances
- 2017-09-08 https://github.slack.com/archives/C1AH2A4R2/p1504896193000293
- 2017-08-29 https://github.slack.com/archives/C0FNNUEV7/p1504012391000061
- 2017-08-29 https://github.slack.com/archives/C0FNNUEV7/p1504004976000176
- 2017-08-22 https://github.slack.com/archives/C0D1T7FD3/p1503417596000360
- 2017-08-10 https://github.slack.com/archives/C0D1T7FD3/p1502373319918115
- 2017-08-01 https://github.slack.com/archives/C0FQLAFDH/p1501634378681778
- 2017-08-01 https://github.slack.com/archives/C0FQLAFDH/p1501634288662667

...

**Comment by stephenyeargin** [comment]
@tcampbell Not 100% on this one, but I was under the impression from various conversations that :octocat: used a completely different implementation of this script.

**Comment by tcampbell** [comment]
https://github.com/hubot-scripts/hubot-pager-me

**Comment by tcampbell** [comment]
@stephenyeargin uh oh, really?  this seemed like the most accurate place for this command.  I admit having a hard time finding the correct repo.
