### ISSUE TITLE
Pager override should prompt you to use `pager me as`

### ISSUE THREAD

**Issue by jasonrudolph** [hubot-scripts/hubot-pager-me#27]
When I ran the following command:

    /pager me redacted 180

I got this error:

> Sorry, I expected to get 1 user back for jason@jasonrudolph.com, but got 0 :sweat:. Can you make sure that is actually a real user on PagerDuty?

Sure enough, that's not my email address on PagerDuty. To resolve the issue, I needed to run this command:

    /pager me as <actual-email-address>

In talking with @technicalpickles, he said:

> There are other code paths that should prompt you to use `/pager me as`. Not sure why the override didn't prompt you.

When the override command can't find your user in PagerDuty, it would be :sparkles: if it prompted to you use `/pager me as` to aid you in resolving the issue.

**Comment by stephenyeargin** [comment]
Fixed with #74, released in `v2.1.12`
