### ISSUE TITLE
[Feature] Add ability to restrict activity to certain services

### ISSUE THREAD

**Issue by stephenyeargin** [hubot-scripts/hubot-pager-me#31]
We have 17 PagerDuty services set up, and some of them can trigger hundreds of errors a day (most auto-resolve quickly). _Editor's note: I could get into the folly of using PagerDuty as a log stashing replacement, but I digress._ The API can only match on incidents that appear on the first page of a list of incidents, and it can only retrieve a maximum of 100 incidents at a time. We have two or three of those  services that actually trigger critical errors, and those are the ones we want to monitor and interact with.

I propose adding a new optional constant, `HUBOT_PAGERDUTY_SERVICES`, that is a comma-delimited string of service IDs to include. If not set, the default behavior of searching all services persists. If it is set, the service ID string is passed on as part of the [relevant request parameters for the API endpoint](https://developer.pagerduty.com/documentation/rest/incidents/list).

**Comment by jnewland** [comment]
Sounds great to me!

**Comment by technicalpickles** [comment]
This seems reasonable.

Another idea I might suggest is https://github.com/hubot-scripts/hubot-pager-me/issues/9 , which would exclude things not assigned to you. If those other services you mentioned aren't triggering alerts assigned to you, then you wouldn't see them.
