### ISSUE TITLE
"Who's on call" returns separate messages for each result

### ISSUE THREAD

**Issue by danoc** [hubot-scripts/hubot-pager-me#46]
We have 15+ rotations, so the script sends many messages at once which kills Hubot because of Slack rate-limiting. It'd be great if it sent all of the rotations in one message.

**Comment by technicalpickles** [comment]
This is tangentially related to https://github.com/hubot-scripts/hubot-pager-me/issues/46 for not returning all results.

**Comment by danoc** [comment]
I think you mean #43. I'll close this since they seem somewhat duplicated.
