### ISSUE TITLE
"Who is on call for xyz?" regex should not capture question mark

### ISSUE THREAD

**Issue by danoc** [hubot-scripts/hubot-pager-me#47]
Currently "Who is on call for mobile?" searches PagerDuty for "mobile?", not "mobile."

Here is a regex that only captures the relevant group:
http://rubular.com/r/iXOlyYDx7o

Let me know if you would like me to submit a PR.

**Comment by stephenyeargin** [comment]
PRs always welcome!

**Comment by stephenyeargin** [comment]
Fixed with #73, released in `v2.1.12`.
