### ISSUE TITLE
Support for v2 API?

### ISSUE THREAD

**Issue by mcg** [hubot-scripts/hubot-pager-me#98]
Looks like the v1 API will be going away July 6, 2017(https://v2.developer.pagerduty.com/v2/docs/api-v2-frequently-asked-questions). Any hope that for v2 support before then?

**Comment by jbaldo** [comment]
Hi, just giving this issue a bump. Is there any interest in upgrading to use the PagerDuty v2 REST API.

The deadline has been pushed out as follows:
- Starting April 24 :: ability to generate new v1 API keys is turned off
- On October 19 :: v1 REST API is decommissioned

**Comment by stephenyeargin** [comment]
I'm no longer working for a group with a PD account, but I would be happy to review code and offer advice.

**Comment by jbaldo** [comment]
@pcoorie awesome! do you have a PR somewhere? @stephenyeargin if you start a trial account and need and need an extension to review, I can help with that.

**Comment by pcoorie** [comment]
Hi @jbaldo and @stephenyeargin 
https://github.com/pcoorie/hubot-v1/pull/1/files

**Comment by silverp1** [comment]
@pcoorie I'll take a look at your PR next week probably, I'd like to help get this across the finish line soon-ish.

**Comment by mwarkentin** [comment]
Doesn't look like you can create V1 API tokens anymore - any word on if v2 support will be landing at some point?

**Comment by silverp1** [comment]
@mwarkentin I've been working on this off and on, still has a bit to go unfortunately.

**Comment by mwarkentin** [comment]
@silverp1 thanks for the update - is there a PR we should keep an eye on or just monitor this issue for updates?

**Comment by silverp1** [comment]
@mwarkentin I'll open up a PR once I have something reasonable, things are mostly broken at the moment so it doesn't seem worth while.

**Comment by biggless** [comment]
https://github.com/hubot-scripts/hubot-pager-me/pull/111

**Comment by stephenyeargin** [comment]
@biggless Added some notes on the PR. I apologize that this has taking so long after you've put so much effort into getting it going.

**Comment by stephenyeargin** [comment]
Calling this one finished with `v3.0.0`.

https://github.com/hubot-scripts/hubot-pager-me/releases/tag/v3.0.0
